# Generated by Django 3.0.7 on 2025-07-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('delivery_time', models.FloatField(help_text='Average delivery time in days')),
                ('defect_rate', models.FloatField(help_text='Defective product rate in %')),
                ('price', models.FloatField(help_text='Average price per unit (Rs.)')),
                ('rating', models.FloatField(blank=True, help_text='Auto-calculated supplier rating (0–10)', null=True)),
            ],
        ),
    ]
